// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZq0maQtWQC1kENnN81xi2qyvFFpWyGFg',
    appId: '1:224079419013:android:463ceae31d8982db53fbec',
    messagingSenderId: '224079419013',
    projectId: 'airdrop-insurance',
    storageBucket: 'airdrop-insurance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrdMTc3KrHvXNs6gZDx1dIyMfd8Xh4aZc',
    appId: '1:224079419013:ios:ccf8a722aa41855253fbec',
    messagingSenderId: '224079419013',
    projectId: 'airdrop-insurance',
    storageBucket: 'airdrop-insurance.appspot.com',
    iosClientId:
        '224079419013-52kegscge1spifnrm9q0kv0b0uj46ad9.apps.googleusercontent.com',
    iosBundleId: 'com.pef.airdropinsurance',
  );
}
